
version: '3.8'

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.clients
    ports:
      - "3000:3000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: mongodb+srv://Admin:Admin2024@cluster0.k07j8e3.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
